import {projectFilter} from './utils';

const testCases = [
  {
    hasSearchText: false,
    hasSelectedCategory: false,
    hasSelectedProjectTypes: false,
    matchesSearchText: false,
    matchesSelectedCategory: false,
    matchesSelectedProjectTypes: false,
    expected: true,
  },
  {
    hasSearchText: false,
    hasSelectedCategory: false,
    hasSelectedProjectTypes: false,
    matchesSearchText: false,
    matchesSelectedCategory: false,
    matchesSelectedProjectTypes: true,
    expected: true,
  },
  {
    hasSearchText: false,
    hasSelectedCategory: false,
    hasSelectedProjectTypes: false,
    matchesSearchText: false,
    matchesSelectedCategory: true,
    matchesSelectedProjectTypes: false,
    expected: true,
  },
  {
    hasSearchText: false,
    hasSelectedCategory: false,
    hasSelectedProjectTypes: false,
    matchesSearchText: false,
    matchesSelectedCategory: true,
    matchesSelectedProjectTypes: true,
    expected: true,
  },
  {
    hasSearchText: false,
    hasSelectedCategory: false,
    hasSelectedProjectTypes: false,
    matchesSearchText: true,
    matchesSelectedCategory: false,
    matchesSelectedProjectTypes: false,
    expected: true,
  },
  {
    hasSearchText: false,
    hasSelectedCategory: false,
    hasSelectedProjectTypes: false,
    matchesSearchText: true,
    matchesSelectedCategory: false,
    matchesSelectedProjectTypes: true,
    expected: true,
  },
  {
    hasSearchText: false,
    hasSelectedCategory: false,
    hasSelectedProjectTypes: false,
    matchesSearchText: true,
    matchesSelectedCategory: true,
    matchesSelectedProjectTypes: false,
    expected: true,
  },
  {
    hasSearchText: false,
    hasSelectedCategory: false,
    hasSelectedProjectTypes: false,
    matchesSearchText: true,
    matchesSelectedCategory: true,
    matchesSelectedProjectTypes: true,
    expected: true,
  },
  {
    hasSearchText: false,
    hasSelectedCategory: false,
    hasSelectedProjectTypes: true,
    matchesSearchText: false,
    matchesSelectedCategory: false,
    matchesSelectedProjectTypes: false,
    expected: false,
  },
  {
    hasSearchText: false,
    hasSelectedCategory: false,
    hasSelectedProjectTypes: true,
    matchesSearchText: false,
    matchesSelectedCategory: false,
    matchesSelectedProjectTypes: true,
    expected: true,
  },
  {
    hasSearchText: false,
    hasSelectedCategory: false,
    hasSelectedProjectTypes: true,
    matchesSearchText: false,
    matchesSelectedCategory: true,
    matchesSelectedProjectTypes: false,
    expected: false,
  },
  {
    hasSearchText: false,
    hasSelectedCategory: false,
    hasSelectedProjectTypes: true,
    matchesSearchText: false,
    matchesSelectedCategory: true,
    matchesSelectedProjectTypes: true,
    expected: true,
  },
  {
    hasSearchText: false,
    hasSelectedCategory: false,
    hasSelectedProjectTypes: true,
    matchesSearchText: true,
    matchesSelectedCategory: false,
    matchesSelectedProjectTypes: false,
    expected: false,
  },
  {
    hasSearchText: false,
    hasSelectedCategory: false,
    hasSelectedProjectTypes: true,
    matchesSearchText: true,
    matchesSelectedCategory: false,
    matchesSelectedProjectTypes: true,
    expected: true,
  },
  {
    hasSearchText: false,
    hasSelectedCategory: false,
    hasSelectedProjectTypes: true,
    matchesSearchText: true,
    matchesSelectedCategory: true,
    matchesSelectedProjectTypes: false,
    expected: false,
  },
  {
    hasSearchText: false,
    hasSelectedCategory: false,
    hasSelectedProjectTypes: true,
    matchesSearchText: true,
    matchesSelectedCategory: true,
    matchesSelectedProjectTypes: true,
    expected: true,
  },
  {
    hasSearchText: false,
    hasSelectedCategory: true,
    hasSelectedProjectTypes: false,
    matchesSearchText: false,
    matchesSelectedCategory: false,
    matchesSelectedProjectTypes: false,
    expected: false,
  },
  {
    hasSearchText: false,
    hasSelectedCategory: true,
    hasSelectedProjectTypes: false,
    matchesSearchText: false,
    matchesSelectedCategory: false,
    matchesSelectedProjectTypes: true,
    expected: false,
  },
  {
    hasSearchText: false,
    hasSelectedCategory: true,
    hasSelectedProjectTypes: false,
    matchesSearchText: false,
    matchesSelectedCategory: true,
    matchesSelectedProjectTypes: false,
    expected: true,
  },
  {
    hasSearchText: false,
    hasSelectedCategory: true,
    hasSelectedProjectTypes: false,
    matchesSearchText: false,
    matchesSelectedCategory: true,
    matchesSelectedProjectTypes: true,
    expected: true,
  },
  {
    hasSearchText: false,
    hasSelectedCategory: true,
    hasSelectedProjectTypes: false,
    matchesSearchText: true,
    matchesSelectedCategory: false,
    matchesSelectedProjectTypes: false,
    expected: false,
  },
  {
    hasSearchText: false,
    hasSelectedCategory: true,
    hasSelectedProjectTypes: false,
    matchesSearchText: true,
    matchesSelectedCategory: false,
    matchesSelectedProjectTypes: true,
    expected: false,
  },
  {
    hasSearchText: false,
    hasSelectedCategory: true,
    hasSelectedProjectTypes: false,
    matchesSearchText: true,
    matchesSelectedCategory: true,
    matchesSelectedProjectTypes: false,
    expected: true,
  },
  {
    hasSearchText: false,
    hasSelectedCategory: true,
    hasSelectedProjectTypes: false,
    matchesSearchText: true,
    matchesSelectedCategory: true,
    matchesSelectedProjectTypes: true,
    expected: true,
  },
  {
    hasSearchText: false,
    hasSelectedCategory: true,
    hasSelectedProjectTypes: true,
    matchesSearchText: false,
    matchesSelectedCategory: false,
    matchesSelectedProjectTypes: false,
    expected: false,
  },
  {
    hasSearchText: false,
    hasSelectedCategory: true,
    hasSelectedProjectTypes: true,
    matchesSearchText: false,
    matchesSelectedCategory: false,
    matchesSelectedProjectTypes: true,
    expected: false,
  },
  {
    hasSearchText: false,
    hasSelectedCategory: true,
    hasSelectedProjectTypes: true,
    matchesSearchText: false,
    matchesSelectedCategory: true,
    matchesSelectedProjectTypes: false,
    expected: false,
  },
  {
    hasSearchText: false,
    hasSelectedCategory: true,
    hasSelectedProjectTypes: true,
    matchesSearchText: false,
    matchesSelectedCategory: true,
    matchesSelectedProjectTypes: true,
    expected: true,
  },
  {
    hasSearchText: false,
    hasSelectedCategory: true,
    hasSelectedProjectTypes: true,
    matchesSearchText: true,
    matchesSelectedCategory: false,
    matchesSelectedProjectTypes: false,
    expected: false,
  },
  {
    hasSearchText: false,
    hasSelectedCategory: true,
    hasSelectedProjectTypes: true,
    matchesSearchText: true,
    matchesSelectedCategory: false,
    matchesSelectedProjectTypes: true,
    expected: false,
  },
  {
    hasSearchText: false,
    hasSelectedCategory: true,
    hasSelectedProjectTypes: true,
    matchesSearchText: true,
    matchesSelectedCategory: true,
    matchesSelectedProjectTypes: false,
    expected: false,
  },
  {
    hasSearchText: false,
    hasSelectedCategory: true,
    hasSelectedProjectTypes: true,
    matchesSearchText: true,
    matchesSelectedCategory: true,
    matchesSelectedProjectTypes: true,
    expected: true,
  },
  {
    hasSearchText: true,
    hasSelectedCategory: false,
    hasSelectedProjectTypes: false,
    matchesSearchText: false,
    matchesSelectedCategory: false,
    matchesSelectedProjectTypes: false,
    expected: false,
  },
  {
    hasSearchText: true,
    hasSelectedCategory: false,
    hasSelectedProjectTypes: false,
    matchesSearchText: false,
    matchesSelectedCategory: false,
    matchesSelectedProjectTypes: true,
    expected: false,
  },
  {
    hasSearchText: true,
    hasSelectedCategory: false,
    hasSelectedProjectTypes: false,
    matchesSearchText: false,
    matchesSelectedCategory: true,
    matchesSelectedProjectTypes: false,
    expected: false,
  },
  {
    hasSearchText: true,
    hasSelectedCategory: false,
    hasSelectedProjectTypes: false,
    matchesSearchText: false,
    matchesSelectedCategory: true,
    matchesSelectedProjectTypes: true,
    expected: false,
  },
  {
    hasSearchText: true,
    hasSelectedCategory: false,
    hasSelectedProjectTypes: false,
    matchesSearchText: true,
    matchesSelectedCategory: false,
    matchesSelectedProjectTypes: false,
    expected: true,
  },
  {
    hasSearchText: true,
    hasSelectedCategory: false,
    hasSelectedProjectTypes: false,
    matchesSearchText: true,
    matchesSelectedCategory: false,
    matchesSelectedProjectTypes: true,
    expected: true,
  },
  {
    hasSearchText: true,
    hasSelectedCategory: false,
    hasSelectedProjectTypes: false,
    matchesSearchText: true,
    matchesSelectedCategory: true,
    matchesSelectedProjectTypes: false,
    expected: true,
  },
  {
    hasSearchText: true,
    hasSelectedCategory: false,
    hasSelectedProjectTypes: false,
    matchesSearchText: true,
    matchesSelectedCategory: true,
    matchesSelectedProjectTypes: true,
    expected: true,
  },
  {
    hasSearchText: true,
    hasSelectedCategory: false,
    hasSelectedProjectTypes: true,
    matchesSearchText: false,
    matchesSelectedCategory: false,
    matchesSelectedProjectTypes: false,
    expected: false,
  },
  {
    hasSearchText: true,
    hasSelectedCategory: false,
    hasSelectedProjectTypes: true,
    matchesSearchText: false,
    matchesSelectedCategory: false,
    matchesSelectedProjectTypes: true,
    expected: false,
  },
  {
    hasSearchText: true,
    hasSelectedCategory: false,
    hasSelectedProjectTypes: true,
    matchesSearchText: false,
    matchesSelectedCategory: true,
    matchesSelectedProjectTypes: false,
    expected: false,
  },
  {
    hasSearchText: true,
    hasSelectedCategory: false,
    hasSelectedProjectTypes: true,
    matchesSearchText: false,
    matchesSelectedCategory: true,
    matchesSelectedProjectTypes: true,
    expected: false,
  },
  {
    hasSearchText: true,
    hasSelectedCategory: false,
    hasSelectedProjectTypes: true,
    matchesSearchText: true,
    matchesSelectedCategory: false,
    matchesSelectedProjectTypes: false,
    expected: false,
  },
  {
    hasSearchText: true,
    hasSelectedCategory: false,
    hasSelectedProjectTypes: true,
    matchesSearchText: true,
    matchesSelectedCategory: false,
    matchesSelectedProjectTypes: true,
    expected: true,
  },
  {
    hasSearchText: true,
    hasSelectedCategory: false,
    hasSelectedProjectTypes: true,
    matchesSearchText: true,
    matchesSelectedCategory: true,
    matchesSelectedProjectTypes: false,
    expected: false,
  },
  {
    hasSearchText: true,
    hasSelectedCategory: false,
    hasSelectedProjectTypes: true,
    matchesSearchText: true,
    matchesSelectedCategory: true,
    matchesSelectedProjectTypes: true,
    expected: true,
  },
  {
    hasSearchText: true,
    hasSelectedCategory: true,
    hasSelectedProjectTypes: false,
    matchesSearchText: false,
    matchesSelectedCategory: false,
    matchesSelectedProjectTypes: false,
    expected: false,
  },
  {
    hasSearchText: true,
    hasSelectedCategory: true,
    hasSelectedProjectTypes: false,
    matchesSearchText: false,
    matchesSelectedCategory: false,
    matchesSelectedProjectTypes: true,
    expected: false,
  },
  {
    hasSearchText: true,
    hasSelectedCategory: true,
    hasSelectedProjectTypes: false,
    matchesSearchText: false,
    matchesSelectedCategory: true,
    matchesSelectedProjectTypes: false,
    expected: false,
  },
  {
    hasSearchText: true,
    hasSelectedCategory: true,
    hasSelectedProjectTypes: false,
    matchesSearchText: false,
    matchesSelectedCategory: true,
    matchesSelectedProjectTypes: true,
    expected: false,
  },
  {
    hasSearchText: true,
    hasSelectedCategory: true,
    hasSelectedProjectTypes: false,
    matchesSearchText: true,
    matchesSelectedCategory: false,
    matchesSelectedProjectTypes: false,
    expected: false,
  },
  {
    hasSearchText: true,
    hasSelectedCategory: true,
    hasSelectedProjectTypes: false,
    matchesSearchText: true,
    matchesSelectedCategory: false,
    matchesSelectedProjectTypes: true,
    expected: false,
  },
  {
    hasSearchText: true,
    hasSelectedCategory: true,
    hasSelectedProjectTypes: false,
    matchesSearchText: true,
    matchesSelectedCategory: true,
    matchesSelectedProjectTypes: false,
    expected: true,
  },
  {
    hasSearchText: true,
    hasSelectedCategory: true,
    hasSelectedProjectTypes: false,
    matchesSearchText: true,
    matchesSelectedCategory: true,
    matchesSelectedProjectTypes: true,
    expected: true,
  },
  {
    hasSearchText: true,
    hasSelectedCategory: true,
    hasSelectedProjectTypes: true,
    matchesSearchText: false,
    matchesSelectedCategory: false,
    matchesSelectedProjectTypes: false,
    expected: false,
  },
  {
    hasSearchText: true,
    hasSelectedCategory: true,
    hasSelectedProjectTypes: true,
    matchesSearchText: false,
    matchesSelectedCategory: false,
    matchesSelectedProjectTypes: true,
    expected: false,
  },
  {
    hasSearchText: true,
    hasSelectedCategory: true,
    hasSelectedProjectTypes: true,
    matchesSearchText: false,
    matchesSelectedCategory: true,
    matchesSelectedProjectTypes: false,
    expected: false,
  },
  {
    hasSearchText: true,
    hasSelectedCategory: true,
    hasSelectedProjectTypes: true,
    matchesSearchText: false,
    matchesSelectedCategory: true,
    matchesSelectedProjectTypes: true,
    expected: false,
  },
  {
    hasSearchText: true,
    hasSelectedCategory: true,
    hasSelectedProjectTypes: true,
    matchesSearchText: true,
    matchesSelectedCategory: false,
    matchesSelectedProjectTypes: false,
    expected: false,
  },
  {
    hasSearchText: true,
    hasSelectedCategory: true,
    hasSelectedProjectTypes: true,
    matchesSearchText: true,
    matchesSelectedCategory: false,
    matchesSelectedProjectTypes: true,
    expected: false,
  },
  {
    hasSearchText: true,
    hasSelectedCategory: true,
    hasSelectedProjectTypes: true,
    matchesSearchText: true,
    matchesSelectedCategory: true,
    matchesSelectedProjectTypes: false,
    expected: false,
  },
  {
    hasSearchText: true,
    hasSelectedCategory: true,
    hasSelectedProjectTypes: true,
    matchesSearchText: true,
    matchesSelectedCategory: true,
    matchesSelectedProjectTypes: true,
    expected: true,
  },
];

describe('compare functions', () => {
  testCases.forEach(
    (
      {
        hasSearchText,
        hasSelectedCategory,
        hasSelectedProjectTypes,
        matchesSearchText,
        matchesSelectedCategory,
        matchesSelectedProjectTypes,
        expected,
      },
      index,
    ) => {
      it(`should return correct result for combination ${index + 1}`, () => {
        const original = projectFilter(
          hasSearchText,
          hasSelectedCategory,
          hasSelectedProjectTypes,
          matchesSearchText,
          matchesSelectedCategory,
          matchesSelectedProjectTypes,
        );
        expect(original).toEqual(expected);
      });
    },
  );
});
